name: Update WoW Versions

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install dependencies
      run: npm install
    - name: Fetch latest versions
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      run: npm run fetch-wow-versions
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet versions.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    - name: Configure Git
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create branch and commit changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        BRANCH_NAME="update-versions-${{ github.run_number }}"
        git checkout -b "$BRANCH_NAME"
        git add versions.json
        git commit -m "chore: update WoW interface versions"
        git push -u origin "$BRANCH_NAME"

    - name: Create Pull Request
      if: steps.changes.outputs.changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
          --title "Update WoW interface versions" \
          --body "This PR updates the WoW interface versions based on the latest data from CurseForge.

          The changes were detected automatically by the scheduled workflow." \
          --base master
